//
//  ShowEventDetailInteractor.swift
//  CleanMap
//
//  Created by Paul Lee on 2018/6/17.
//  Copyright (c) 2018年 Paul Lee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowEventDetailBusinessLogic {
  func doSomething(request: ShowEventDetail.Something.Request)
  func getEvent(request: ShowEventDetail.getEvent.Request)
}

protocol ShowEventDetailDataStore {
  var eventToBeShown: Event? { get set }
}

class ShowEventDetailInteractor: ShowEventDetailBusinessLogic, ShowEventDetailDataStore {
  var eventToBeShown: Event?
  var presenter: ShowEventDetailPresentationLogic?
  var worker: ShowEventDetailWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: ShowEventDetail.Something.Request) {
    worker = ShowEventDetailWorker()
    worker?.doSomeWork()

    let response = ShowEventDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
  
  
  //MARK: - get event
  func getEvent(request: ShowEventDetail.getEvent.Request) {
    let response = ShowEventDetail.getEvent.Response(event: eventToBeShown!)
    presenter?.presentDetailedEvent(response: response)
    
  }
  
}
