//
//  ShowEventDetailModels.swift
//  CleanMap
//
//  Created by Paul Lee on 2018/6/17.
//  Copyright (c) 2018年 Paul Lee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoogleMaps
enum ShowEventDetail {
  // MARK: Use cases

  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
  
  enum getEvent {
    struct Request {
    
    }
    struct Response {
      var event: Event
    
    }
    struct ViewModel {
      struct DisplayedEvent {
        var name: String
        var date: String
        var startAndEndTime: String
        var venueName: String
        var address: String
        var hosters: String
        var marker: GMSMarker
        var camera: GMSCameraPosition
      }
      var displayedEvent: DisplayedEvent
    }
  }
}
