//
//  ListEventsWorkerTests.swift
//  CleanMap
//
//  Created by Paul Lee on 2018/5/30.
//  Copyright (c) 2018年 Paul Lee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanMap
import XCTest

class ListEventsWorkerTests: XCTestCase {
  // MARK: Subject under test

  var sut: ListEventsWorker!

  // MARK: Test lifecycle

  override func setUp() {
    super.setUp()
    setupListEventsWorker()
  }

  override func tearDown() {
    super.tearDown()
  }

  // MARK: Test setup

  func setupListEventsWorker() {
    sut = ListEventsWorker()
  }

  // MARK: Test doubles

  // MARK: Tests

}
